spring.application.name=trimly-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/trimly
spring.datasource.username=postgres
spring.datasource.password=Savi@333
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

trimly.jwt.secret=75d10aed91be7fb7b08689d382bb916a7bd10cca9f463d300035c42d27c313c5
trimly.jwt.expiration-ms=86400000
